name: idpfold2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - pyg
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.4.1
  - pyg::pyg=2.6.1
  - bioconda::mmseqs2=17.b804f
  - pip:
    - einops==0.6
    - dm-tree==0.1.8
    - loguru==0.7.2
    - hydra-core==1.3.1
    - numpy==1.23.5
    - pandas==1.5.3
    - biotite==0.41.0
    - biopandas==0.5.1
    - wget==3.2
    - tqdm==4.66.4
    - cpdb-protein
    - biopython
